### ISSUE TITLE
Mysqldump won't go through if your sql database password has spaces in it

### ISSUE THREAD

**Issue by guiand888** [jamesrascal/wordpress-backup#5]
In V1.9, mysqldump won't go through if your sql database password has spaces in it.

The following error will show up:

> mysqldump: Got error: 1045: "Access denied for user 'username'@'localhost' (using password: YES)" when trying to connect

**Steps to reproduce:** use a database password with spaces in it.
It's confirmed to be induced by spaces in the password as changing my password fixed this.

I tried to fix it with double-quoting the password variable in the mysqldump command but that didn't work, and my coding skills are really limited, so all I can do is report it.

**Comment by jamesrascal** [comment]
This should be something that is easy to fix. 

I am looking through the script now and you should be able to modify the MySQL command to include ' or "
